spring:
  profiles:
    active: local
bot:
  qq:
  password:
  #ANDROID_PHONE,ANDROID_PAD,ANDROID_WATCH,IPAD,MACOS;
  protocol:
  listeningGroup:
    - 123456
    - 12345
  v2token:
  workdir:
  proxy:
    host: localhost
    port: 7890
  split: ' '
